/* ===================================================
   さかなつりゲーム — ことばリスト
   ここを編集するだけで、30種類・100種類の単語を変更できます。
   長い順（文字数が多いもの→少ないもの）に並べてください。
   =================================================== */

/* ---------- 30種類 ---------- */
const WORD_DICT = [
  // 4文字（+15）
  { word:'きんぎょ', bonus:15, emoji:'🐡' },
  { word:'ししゃも', bonus:15, emoji:'🐟' },
  { word:'あんこう', bonus:15, emoji:'🐟' },
  { word:'かわはぎ', bonus:15, emoji:'🐟' },
  { word:'どじょう', bonus:15, emoji:'🐟' },
  // 3文字（+10）
  { word:'まぐろ',   bonus:10, emoji:'🐟' },
  { word:'さんま',   bonus:10, emoji:'🐟' },
  { word:'かつお',   bonus:10, emoji:'🐟' },
  { word:'いわし',   bonus:10, emoji:'🐟' },
  { word:'うなぎ',   bonus:10, emoji:'🐍' },
  { word:'ひらめ',   bonus:10, emoji:'🐟' },
  { word:'かれい',   bonus:10, emoji:'🐟' },
  { word:'めだか',   bonus:10, emoji:'🐟' },
  { word:'ほっけ',   bonus:10, emoji:'🐟' },
  { word:'にしん',   bonus:10, emoji:'🐟' },
  { word:'すずき',   bonus:10, emoji:'🐟' },
  { word:'はまち',   bonus:10, emoji:'🐟' },
  { word:'さわら',   bonus:10, emoji:'🐟' },
  // 2文字（+5）
  { word:'さけ',     bonus: 5, emoji:'🐟' },
  { word:'さば',     bonus: 5, emoji:'🐟' },
  { word:'あじ',     bonus: 5, emoji:'🐟' },
  { word:'たい',     bonus: 5, emoji:'🐟' },
  { word:'ぶり',     bonus: 5, emoji:'🐟' },
  { word:'たら',     bonus: 5, emoji:'🐟' },
  { word:'ふぐ',     bonus: 5, emoji:'🐡' },
  { word:'こい',     bonus: 5, emoji:'🐟' },
  { word:'いか',     bonus: 5, emoji:'🦑' },
  { word:'たこ',     bonus: 5, emoji:'🐙' },
  { word:'えび',     bonus: 5, emoji:'🦐' },
  { word:'かに',     bonus: 5, emoji:'🦀' },
];

/* ---------- 100種類 ---------- */
const WORD_DICT_100 = [
  // 9文字（+40）
  { word:'ちょうちんあんこう', bonus:40, emoji:'🐟' },
  { word:'りゅうぐうのつかい', bonus:40, emoji:'🐟' },
  // 8文字（+35）
  { word:'ちょうちょううお',   bonus:35, emoji:'🐠' },
  // 7文字（+30）
  { word:'かたくちいわし',     bonus:30, emoji:'🐟' },
  { word:'たつのおとしご',     bonus:30, emoji:'🐴' },
  // 6文字（+25）
  { word:'うるめいわし',       bonus:25, emoji:'🐟' },
  { word:'きはだまぐろ',       bonus:25, emoji:'🐟' },
  { word:'めばちまぐろ',       bonus:25, emoji:'🐟' },
  { word:'じんべえざめ',       bonus:25, emoji:'🦈' },
  { word:'なんようはぎ',       bonus:25, emoji:'🐠' },
  { word:'しーらかんす',       bonus:25, emoji:'🐟' },
  // 5文字（+20）
  { word:'くろまぐろ',         bonus:20, emoji:'🐟' },
  { word:'きんめだい',         bonus:20, emoji:'🐟' },
  // 4文字（+15）
  { word:'きんぎょ', bonus:15, emoji:'🐡' },
  { word:'ししゃも', bonus:15, emoji:'🐟' },
  { word:'あんこう', bonus:15, emoji:'🐟' },
  { word:'かわはぎ', bonus:15, emoji:'🐟' },
  { word:'どじょう', bonus:15, emoji:'🐟' },
  { word:'まいわし', bonus:15, emoji:'🐟' },
  { word:'ごまさば', bonus:15, emoji:'🐟' },
  { word:'しまあじ', bonus:15, emoji:'🐟' },
  { word:'しろさけ', bonus:15, emoji:'🐟' },
  { word:'べにざけ', bonus:15, emoji:'🐟' },
  { word:'ぎんざけ', bonus:15, emoji:'🐟' },
  { word:'にじます', bonus:15, emoji:'🐟' },
  { word:'わかさぎ', bonus:15, emoji:'🐟' },
  { word:'とびうお', bonus:15, emoji:'🐟' },
  { word:'かんぱち', bonus:15, emoji:'🐟' },
  { word:'ひらまさ', bonus:15, emoji:'🐟' },
  { word:'いしだい', bonus:15, emoji:'🐟' },
  { word:'くろだい', bonus:15, emoji:'🐟' },
  { word:'あまだい', bonus:15, emoji:'🐟' },
  { word:'のどぐろ', bonus:15, emoji:'🐟' },
  { word:'ほうぼう', bonus:15, emoji:'🐟' },
  { word:'まんぼう', bonus:15, emoji:'🐡' },
  { word:'くまのみ', bonus:15, emoji:'🐠' },
  { word:'ぺんぎん', bonus:15, emoji:'🐧' },
  { word:'あざらし', bonus:15, emoji:'🦭' },
  { word:'うみがめ', bonus:15, emoji:'🐢' },
  // 3文字（+10）
  { word:'まぐろ', bonus:10, emoji:'🐟' },
  { word:'さんま', bonus:10, emoji:'🐟' },
  { word:'かつお', bonus:10, emoji:'🐟' },
  { word:'いわし', bonus:10, emoji:'🐟' },
  { word:'うなぎ', bonus:10, emoji:'🐍' },
  { word:'ひらめ', bonus:10, emoji:'🐟' },
  { word:'かれい', bonus:10, emoji:'🐟' },
  { word:'めだか', bonus:10, emoji:'🐟' },
  { word:'ほっけ', bonus:10, emoji:'🐟' },
  { word:'にしん', bonus:10, emoji:'🐟' },
  { word:'すずき', bonus:10, emoji:'🐟' },
  { word:'はまち', bonus:10, emoji:'🐟' },
  { word:'さわら', bonus:10, emoji:'🐟' },
  { word:'まさば', bonus:10, emoji:'🐟' },
  { word:'まあじ', bonus:10, emoji:'🐟' },
  { word:'やまめ', bonus:10, emoji:'🐟' },
  { word:'いわな', bonus:10, emoji:'🐟' },
  { word:'なまず', bonus:10, emoji:'🐟' },
  { word:'あなご', bonus:10, emoji:'🐍' },
  { word:'いさき', bonus:10, emoji:'🐟' },
  { word:'めじな', bonus:10, emoji:'🐟' },
  { word:'めばる', bonus:10, emoji:'🐟' },
  { word:'かさご', bonus:10, emoji:'🐟' },
  { word:'おこぜ', bonus:10, emoji:'🐟' },
  { word:'いるか', bonus:10, emoji:'🐬' },
  { word:'くじら', bonus:10, emoji:'🐳' },
  { word:'しゃち', bonus:10, emoji:'🐋' },
  { word:'あしか', bonus:10, emoji:'🦭' },
  { word:'らっこ', bonus:10, emoji:'🦦' },
  { word:'くらげ', bonus:10, emoji:'🪼' },
  { word:'さんご', bonus:10, emoji:'🪸' },
  { word:'ひとで', bonus:10, emoji:'⭐' },
  { word:'なまこ', bonus:10, emoji:'🐟' },
  { word:'ほたて', bonus:10, emoji:'🫘' },
  { word:'あさり', bonus:10, emoji:'🐚' },
  { word:'しじみ', bonus:10, emoji:'🐚' },
  { word:'あわび', bonus:10, emoji:'🐚' },
  { word:'さざえ', bonus:10, emoji:'🐚' },
  // 2文字（+5）
  { word:'さけ', bonus: 5, emoji:'🐟' },
  { word:'さば', bonus: 5, emoji:'🐟' },
  { word:'あじ', bonus: 5, emoji:'🐟' },
  { word:'たい', bonus: 5, emoji:'🐟' },
  { word:'ぶり', bonus: 5, emoji:'🐟' },
  { word:'たら', bonus: 5, emoji:'🐟' },
  { word:'ふぐ', bonus: 5, emoji:'🐡' },
  { word:'こい', bonus: 5, emoji:'🐟' },
  { word:'いか', bonus: 5, emoji:'🦑' },
  { word:'たこ', bonus: 5, emoji:'🐙' },
  { word:'えび', bonus: 5, emoji:'🦐' },
  { word:'かに', bonus: 5, emoji:'🦀' },
  { word:'ます', bonus: 5, emoji:'🐟' },
  { word:'あゆ', bonus: 5, emoji:'🐟' },
  { word:'はも', bonus: 5, emoji:'🐍' },
  { word:'きす', bonus: 5, emoji:'🐟' },
  { word:'はぜ', bonus: 5, emoji:'🐟' },
  { word:'ぼら', bonus: 5, emoji:'🐟' },
  { word:'くえ', bonus: 5, emoji:'🐟' },
  { word:'さめ', bonus: 5, emoji:'🦈' },
  { word:'えい', bonus: 5, emoji:'🐟' },
  { word:'うに', bonus: 5, emoji:'🦔' },
  { word:'かき', bonus: 5, emoji:'🦪' },
];
